kind=defined
names=assert_exception
visibility=public

--- assert_exception(exception[, message]) { ... }

ブロックを実行中に例外 exception が発生することを表明します。
ブロックを実行しても例外 exception が発生しなかったら
このアサーションは失敗します。
message はアサート失敗時のエラーメッセージです。

